/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package word_guessing_game;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class AppTest {
    @Test public void appRunsGame() {
        WordChoser mockedChoser = mock(WordChoser.class);
        when(mockedChoser.getRandomWordFromDictionary()).thenReturn("LONDON");
        Game game = new Game(mockedChoser);
        assertEquals(game.guessLetter('L'), "Wrong!");
    }
}
