/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package word_guessing_game;

import java.util.*;

public class App {
    public String getWordAndAttempts() {
        WordChoser wc = new WordChoser();

        Game playerOne = new Game(wc);
        Game playerTwo = new Game(wc);

        Scanner scan = new Scanner(System.in);

        System.out.println("Enter name for Player One: ");
        String playerOneName = scan.nextLine();

        System.out.println("Enter name for Player Two: ");
        String playerTwoName = scan.nextLine();

        System.out.printf("Welcome, today's words are: \n%s: %s \n%s: %s \n"
        , playerOneName
        , playerOne.getWordToGuess(' ')
        , playerTwoName
        , playerTwo.getWordToGuess(' '));

        while (playerOne.attempts > 0 && playerOne.gameIsWon() == false && playerTwo.attempts > 0 && playerTwo.gameIsWon() == false) {
            
            System.out.printf("%s, please enter a letter (%s attempts remaining) \n", playerOneName, playerOne.attempts);
            Character letterForOne = scan.next().charAt(0);
            System.out.println(playerOne.guessLetter(letterForOne));
            playerOne.attempts--;
            System.out.println(playerOne.getWordToGuess(letterForOne));
            if (playerOne.gameIsWon()) {
                break;
            }

            System.out.printf("%s, please enter a letter (%s attempts remaining) \n", playerTwoName, playerTwo.attempts);
            Character letterForTwo = scan.next().charAt(0);
            System.out.println(playerTwo.guessLetter(letterForTwo));
            playerTwo.attempts--;
            System.out.println(playerTwo.getWordToGuess(letterForTwo));
            if (playerTwo.gameIsWon()) {
                break;
            }
        }
        scan.close();
        if (playerOne.gameIsWon()) {
            return "Player One has won!";
        }
        else if (playerTwo.gameIsWon()) {
            return "Player Two has won!";
        }
        else if (playerOne.attempts == 0) {
            return "Player One has lost!";
        }
        else if (playerTwo.attempts == 0) {
            return "Player Two has lost!";
        }
        return "The game has ended!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getWordAndAttempts());
    }
}
